DNC in the shell
xivintheshell/xivintheshell pull request #65
Opened 2024-11-17 22:51 UTC by AkairyuGestalter

You can shell DNC if you want to, you can leave spreadsheets behind~

I updated the URL that the icon downloader script pulls from to use the updated xivapi beta site, which is the one that's actually being maintained going forward.

Also included is some work to allow actions to affect/be affected by multiple cooldowns for things like GCDs with an associated longer cooldown (ie. Standard/Technical/MCH tools), or abilities that share a cooldown in-game (ie. Closed Position and Ending).

Longer term, we should probably refactor this to more closely match game state which defines cooldowns by group, and any given action can be affected by an array of coldowngroups, but this should be sufficient for any near-term use.

2024-11-17 23:44 UTC, miyehn commented
:0 just poked around a bit and I saw this:
![image](https://github.com/user-attachments/assets/c20248dc-bb1c-49c1-a195-81df29a6826d)
I don't think we should use the green GCD bar to indicate anything other than GCD. The green GCD bars and purple cast bars are displayed like they do now to indicate whichever is longer will block the next skill/GCD, but in this case this green bar isn't blocking anything. And may overlap with later GCDs and make it hard to tell how long a skill takes.

I don't play dancer and maybe it doesn't matter as much specifically for dancers, but I think we should keep the visuals consistent whenever possible, so players using other jobs don't get confused.
* How is ths status shown in game? Is it a buff? If so can we also switch to using a buff instead and get rid of this buff after `Standard Finish`?

2024-11-18 00:49 UTC, AkairyuGestalter commented
That's probably an unintentional side effect of setting up the additional cooldown handling for Standard's 30s cooldown... I didn't really pay attention to that since I was focused on making things work right. I'll take a look to see if I can figure out how to fix that

2024-11-18 07:05 UTC, zqsz-xiv reviewed
Got a few comments, otherwise LGTM! Can you try to also fix the indentation in `DNC.ts`? It seems like there's a mix of spaces/tabs that makes it hard to read in the github editor (partly my fault, since my editor is set to spaces by default and I think miyehn uses tabs, and I forgot to convert indentation on some of the new files I made).

2024-11-19 02:56 UTC, AkairyuGestalter commented on src/Game/Jobs/DNC.ts
> +makeGCD_DNC(SkillName.SingleTechnicalFinish, 70, {
I kept Quadruple Technical Finish split out cause it has some extra handling, but not a bad idea for the others. Done.

2024-11-19 02:59 UTC, AkairyuGestalter commented on src/Game/Jobs/DNC.ts
> +        if (resource.availableAmount() === resource.maxValue) {
Yeah, it should be (more that you can be at 95 Esprit and gain 10). I did Feathers first which this works fine for, but Esprit breaks that original coding.

2024-11-19 03:37 UTC, zqsz-xiv reviewed
Poked around a bit more, found a couple console errors:
- Need to register `TechnicalBonus` and `StandardBonus` ResourceTypes
- Need to stop the lucid tick event from being registered in `GameState.ts` (see https://github.com/xivintheshell/xivintheshell/blob/fc02ef11fb42d2ed43bc55bb5c809c649c274dfc/src/Game/GameState.ts#L183-L188), I'll refactor it out later
I'm also getting a `Cannot read properties of undefined (reading 'warningOnTimeout')` from [this line](https://github.com/xivintheshell/xivintheshell/blob/3f5da45ab177f676a8b46d722eade5b03496f783/src/Game/GameState.ts#L590) in `GameState::enqueueResourceDrop`. I think it's caused by those resources not being registered, but if you could add a `?` to `rscInfo.warningOnTimeout` to prevent the exception that would be helpful (missing resources already raise a console error).

Also, please double-check indentation (or just get your editor to do a conversion) in `Game/Jobs/DNC.ts`, some stuff is showing up weirdly in the github editor and it looks like there's still a mix of tabs/spaces
![image](https://github.com/user-attachments/assets/e7fb8d41-db75-4fba-88be-a0ee2c7681ca).

2024-11-19 03:37 UTC, zqsz-xiv commented on src/Game/Jobs/DNC.ts
> +    recastTime: (state) => state.config.adjustedSksGCD(),
Doesn't Tillana not scale to your GCD in 7.x?

2024-11-19 03:37 UTC, zqsz-xiv commented on src/Components/PlaybackControl.tsx
> +		this.updateSksTaxPreview = (sksStr: string, fpsStr: string, levelStr: string) => {
Looks like you missed a call to this in `this.setJob`, since the preview's showing as "n/a" on page reload.

2024-11-19 03:39 UTC, zqsz-xiv commented
Here's the file I'm using to get the exception, I see the exception after loading this and then pressing any GCD.

[dnc_error_after_one_more_button.txt](https://github.com/user-attachments/files/17808920/dnc_error_after_one_more_button.txt)

2024-11-19 03:50 UTC, zqsz-xiv commented on src/changelog.json
> +		"date": "11/17/24",
remember to update this with whatever date it gets merged, right now react is complaining because it's duplicating a key from a different changelog entry

2024-11-19 05:12 UTC, miyehn requested changes
Not done reviewing yet but:
![image](https://github.com/user-attachments/assets/f516bb7e-e47b-4a53-9d2b-c069bf9a235c)
I guess DNC shouldn't be ticking lucid dreaming? 😂

2024-11-19 05:12 UTC, miyehn commented on src/Components/PlaybackControl.tsx
> +						const spellSpeed = stats.get("SPS") ?? baseSpeed
nit: type looks kinda... unnecessarily mixed in these couple of lines. Maybe just stick to either string or number? And would also be able to get rid of the exclamation marks on lines 595 and 596 🤔

2024-11-19 05:12 UTC, miyehn commented on src/Components/PlaybackControl.tsx
> +							importedFields: ["job", "level", "spellSpeed", "skillSpeed", "criticalHit", "directHit", "determination"],
Also, does etro not always import both SPS and SKS? Does that mean only one of the two should be in `importedFields` here? :0

2024-11-19 05:15 UTC, miyehn commented
Also no.... let's not leave the huge `minHeight` as is... I will figure something out......

2024-11-19 05:23 UTC, zqsz-xiv commented on src/Components/PlaybackControl.tsx
> +							importedFields: ["job", "level", "spellSpeed", "skillSpeed", "criticalHit", "directHit", "determination"],
It looks like you're right, etro gives only one of the two, but xivgear gives both.

2024-11-19 07:10 UTC, miyehn commented
(continuation from discord)
Seems like even to do something special for DNC is going to require a tiny bit of refactor... I guess, for this PR can we have the huge `minHight` just for DNC but not other jobs? And I'll make another PR to implement this:
![image](https://github.com/user-attachments/assets/efd4e766-6c87-4b84-9a4e-397af2c9d6c1)
Or alternatively merge the `minHeight` as-is but don't deploy yet...

2024-11-19 08:26 UTC, miyehn reviewed
I didn't check the job implementation specifics but others changes mostly look good to me👌

2024-11-19 08:26 UTC, miyehn commented on src/Game/GameConfig.ts
>  	adjustedGCD(baseGCD: number = 2.5, speedBuff?: ResourceType) {
nit: we can rename this one too, `adjustedGCD` -> `adjustedSpsGCD`

2024-11-19 23:48 UTC, AkairyuGestalter commented on src/Components/PlaybackControl.tsx
> +			sksGcdPreview: "n/a",
I was somewhat intentionally leaving the existing properties as-is so we didn't have to do change them everywhere else.

2024-11-20 00:46 UTC, AkairyuGestalter commented on src/Components/PlaybackControl.tsx
> +						const spellSpeed = stats.get("SPS") ?? baseSpeed
the exclamation points were already there before I make the change, and I'm not familiar with what that notation doeas, so I'll leave that alone, but I can at least toString the retrieval of the base speed so we're always dealing with strings for the speed stats themselves

2024-11-20 00:53 UTC, AkairyuGestalter commented on src/changelog.json
> +		"date": "11/17/24",
Done

2024-11-20 00:54 UTC, AkairyuGestalter commented on src/Components/PlaybackControl.tsx
> +		this.updateSksTaxPreview = (sksStr: string, fpsStr: string, levelStr: string) => {
Yeah, I'd missed that when I was creating the sks version. Fixed.

2024-11-20 00:55 UTC, AkairyuGestalter commented on src/Game/Jobs/DNC.ts
> +makeGCD_DNC(SkillName.SingleTechnicalFinish, 70, {
Actually ended up compressing both Standard and Technical finish action creation into their own array foreaches, with some conditionals to handle bailing early on no-steps and figuring out which bonus level to apply dynamically based on executed steps

2024-11-20 00:57 UTC, AkairyuGestalter commented
Changes should all be present. If there are more indent level problems we should consider setting up eslint rules to enforce whichever flavor we want, and can also set up vscode rules to automatically fix lint errors on save so we don't have this problem in the future.

The minHeight change is being left in for now since the code locus that was made at has no notion of the current job, so I can't condition it as such. Plus it seems there's other ideas baking anyways...

2024-11-20 01:33 UTC, zqsz-xiv commented on src/Components/PlaybackControl.tsx
> +						const spellSpeed = stats.get("SPS") ?? baseSpeed
`!` is a type system escape hatch that asserts the value cannot be null/undefined. It's no longer necessary here because `stats.get("SPS") ?? baseSpeed` cannot be undefined, where previously `stats.get("SPS")` could have returned undefined.

2024-11-20 01:37 UTC, zqsz-xiv commented
> If there are more indent level problems we should consider setting up eslint rules to enforce whichever flavor we want, and can also set up vscode rules to automatically fix lint errors on save so we don't have this problem in the future.

Yeah... we should probably wait until a couple weeks after FRU and the codebase settles down so we don't introduce a bunch of merge conflicts due to linting though. Might also want to make precommit hook for this purpose.

> The minHeight change is being left in for now since the code locus that was made at has no notion of the current job,

We have a hacky way to get the currently displayed job with `controller.getActiveJob()`. It's unidiomatic but it should work, and I think it's worth doing because the big minheight does make the other jobs look kinda weird.

2024-11-20 01:48 UTC, zqsz-xiv commented
Also, damage table still isn't rendering modifiers correctly: should be an easy fix, you'll just need to modify the `buffName` and `BuffTag` functions in `src/Components/DamageStatistics.tsx` (https://github.com/xivintheshell/xivintheshell/wiki/Adding-a-new-job#the-damage-table).

![image](https://github.com/user-attachments/assets/422159e7-a204-4698-9c35-2c16af21f14f)

2024-11-20 03:41 UTC, miyehn commented on src/Components/DamageStatistics.tsx
> +				<div style={cell(19)}>{tags}</div>
I will get home later and check if changing the table layout is okay here- the previous ones worked fine for BLM, PCT and RDM, maybe DNC just has more buffs.
But also, if possible I'd advocate for having as few tags as possible, and only leave the ones that are actually helpful. There was a related discussion [here ](https://github.com/xivintheshell/xivintheshell/pull/43#pullrequestreview-2383992217)(need to expand resolved)

2024-11-20 04:56 UTC, miyehn commented on src/Game/Potency.ts
> +		critFactor: 0.2,
rip time for us to rename them to be clear :0

2024-11-20 04:58 UTC, miyehn approved these changes
Anyway I might clean up some nits myself later but I don't see more blocking issues 🙏

2024-11-20 05:02 UTC, miyehn commented
![image](https://github.com/user-attachments/assets/86c3cced-0f3d-41a3-abd2-b14fd7d9eb40)
There's this but should be quick to fix; I can fix it later too

2024-11-21 02:35 UTC, merged