Refactor TraitList into Jobs/Common.ts
xivintheshell/xivintheshell pull request #69
Opened 2024-11-23 05:05 UTC by misterperson

Not sure if there's a better way to do this that avoids an apparent circular import between Common and Traits.
I tried to define TraitName elsewhere and only build the map from Trait.ts, but I was running into static initialization errors with `Trait:buildList()` referencing `Common.ts:TraitList` before it was initialized.

2024-11-24 08:00 UTC, zqsz-xiv requested changes
Thanks for the PR!

> I was running into static initialization errors with Trait:buildList() referencing Common.ts:TraitList before it was initialized

Would it be possible to split `TraitName` into stuff like `BLMTraitName` up like we do for `SkillName`, and keep declarations like `BLMTraitList` as before? You should be able to refer to `BLMTraitName` as the keys of the `TraitList` objects, possibly with some extra casting in the union in `Common.ts`.

2024-11-24 15:32 UTC, misterperson commented
> Would it be possible to split `TraitName` into stuff like `BLMTraitName` up like we do for `SkillName`, and keep declarations like `BLMTraitList` as before? You should be able to refer to `BLMTraitName` as the keys of the `TraitList` objects, possibly with some extra casting in the union in `Common.ts`.

Maybe. My main reason for not splitting up` TraitName` was that numeric enums would start at 1 and count up, so joining multiple enums would result in duplicate keys in the global TraitList. Although, that does point out the dubious nature of a global trait list. Tank Melee Mastery (Endwalker) is unlocked prior to Melee DPS Melee Mastery (Dawntrail).

I'll try splitting it up in a separate commit and get feedback.

2024-11-24 16:20 UTC, misterperson commented
I do have a good question about shared trait names...

Tanks get Melee Mastery at level 84
Dragoon gets Melee Mastery at level 94
Monk gets Melee Mastery at 84

Healers currently have a Magick Mastery at 94
Wouldn't put it past SE to add a Magick Mastery to a magical ranged job later on...

How should we differentiate these traits? I know that for EW and DT, the potency trait for each job is at level X4. But traits below 80 are just plain inconsistent (although they are at least unique AFAIK).

2024-11-24 21:06 UTC, zqsz-xiv commented
> My main reason for not splitting up TraitName was that numeric enums would start at 1 and count up, so joining multiple enums would result in duplicate keys in the global TraitList

Fair point, I forgot that since traits aren't exposed to users we don't make it a string enum. One possible workaround would be to start the discriminant at a really high value, like giving BLM `EnhancedEnochianII = 0`, PCT `PictomanyMasteryII = 100`, RDM `EnhancedDisplacement = 200`, etc. so they never conflict assuming there won't be 100 traits per job, but this is a bit hacky.

> I'd personally lean towards something like MeleeMasterMNK/MeleeMasterDRG and the like where jobs have the same trait name at different levels, or MeleeMasteryTank if there's a shared name where the whole role gets it at once.

Agreed, this seems reasonable. We should also add a role trait section for stuff like Enhanced Addle/Feint.

2024-11-25 23:58 UTC, misterperson commented
Ugh, random whitespace changes. Does this repository have a formatter?

2024-11-26 00:18 UTC, misterperson commented
This needs a test to verify that all enum members have unique names, but I'm not sure it would quite work the way that's expected in Typescript since enums are really just Objects.

2024-11-26 00:39 UTC, misterperson commented on src/traits.test.js
> +        expect([name,value]).toBeUnlockedAtLevelCap();
Oh, this test doesn't work as expected because `hasUnlocked` returns `true` for non-existent traits.

2024-11-26 01:24 UTC, zqsz-xiv commented
> Does this repository have a formatter?

Unfortunately no, we didn't have one prior to the BLM/PCT merge, and we decided to hold off on adding one since a couple other people were working on additional jobs and we didn't want to create merge conflicts for them. I'll look into setting it up some time after FRU release when things have calmed down a bit.

2024-11-26 02:15 UTC, misterperson commented
Updated for RPR

2024-11-29 14:20 UTC, miyehn commented
@zqsz-xiv (psst, in case you haven't seen the updates yet 👀)

2024-11-29 21:19 UTC, zqsz-xiv commented
Sorry, got waylaid by FRU prog. Overall looks good to me, just two comments:
- Is there any particular reason for starting BLM traits at 9001? The prefixes aren't contiguous anymore and it might cause a bit of confusion when we add our next couple jobs.
- I'd prefer for trait numbers to start 0-indexed (e.g. Never = 0, then each job starts at 1000/2000, etc. rather than 1001/2001).

2024-11-30 00:07 UTC, misterperson commented
BLM can be reordered to 1000-1999. Traits can be changed to zero-indexed. Just wanted to insert some humor into the code :p (see `./Constants/BLM.ts`)

The unit tests for traits will verify there are no conflicts between the indices of traits when additional jobs are added.

I can get a fix up pushed later today. Currently stuck at the office writing performance reviews and waiting for a car to charge.

________________________________
From: zqsz-xiv ***@***.***>
Sent: Friday, November 29, 2024 1:20:24 PM
To: xivintheshell/xivintheshell ***@***.***>
Cc: NoHomeLike192.168.8.1 ***@***.***>; Author ***@***.***>
Subject: Re: [xivintheshell/xivintheshell] Refactor TraitList into Jobs/Common.ts (PR #69)


Sorry, got waylaid by FRU prog. Overall looks good to me, just two comments:

  *   Is there any particular reason for starting BLM traits at 9001? The prefixes aren't contiguous anymore and it might cause a bit of confusion when we add our next couple jobs.
  *   I'd prefer for trait numbers to start 0-indexed (e.g. Never = 0, then each job starts at 1000/2000, etc. rather than 1001/2001).

—
Reply to this email directly, view it on GitHub<https://github.com/xivintheshell/xivintheshell/pull/69#issuecomment-2508672897>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAK3534Q7TN52FAPSNR7REL2DDLBLAVCNFSM6AAAAABSKVRJ3CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMBYGY3TEOBZG4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-11-30 20:42 UTC, zqsz-xiv approved these changes
Looks good, thanks!

2024-11-30 20:43 UTC, merged