Add Warrior to Shell Jobs
xivintheshell/xivintheshell pull request #80
Opened 2024-12-02 19:56 UTC by misterperson

Fight logs need to be reviewed to determine application times for each ability, but the bulk of WAR is in.
I will wait for other PRs to get in to unmark this as a draft.

[WAR_240_GCD_FRU_P1.json](https://github.com/user-attachments/files/17983234/WAR_240_GCD_FRU_P1.json)
![WAR_240_GCD_FRU_P1](https://github.com/user-attachments/assets/582cdee0-e377-4c22-bf04-6448975a4103)

2024-12-02 20:01 UTC, misterperson commented on src/Components/ColorTheme.tsx
> +				beastGauge: "#ffba00",
This fails the WebAIM contrast checker test. Will hue shift this towards orange and darken.

2024-12-02 20:07 UTC, misterperson commented on src/Game/Jobs/WAR.ts
> +});
Is there a way to do this without creating an event to restore 1 second of cooldown to enabling Defiance?
* Enabling tank stance puts disabling tank stance on cooldown for 2 seconds.
* Disabling tank stance puts tank stance on cooldown for 1 second.

2024-12-02 20:08 UTC, misterperson commented on src/Game/Jobs/WAR.ts
> +makeAbility_WAR(WARSkillName.Orogeny, 64, WARCooldownType.cd_Upheaval, {
Oops, I believe Orogeny is Endwalker

2024-12-02 20:09 UTC, misterperson commented on src/Game/Jobs/WAR.ts
> +        // To reviewers: should this be done through an internal trait?
This is NOT done through a trait in-game.

2024-12-02 20:19 UTC, misterperson commented on src/Game/Constants/WAR.ts
> +    SteelCyclone = "Steel Cyclone", // Lv45-71
Steel Cyclone is actually downgraded Decimate...

2024-12-02 20:21 UTC, misterperson commented on src/Game/Jobs/WAR.ts
> +    cooldown: 1.0,
Actually have to double-check this. Will probably be relevant in DT field op when Inner Release can have CDR or be refreshed.

2024-12-03 00:01 UTC, zqsz-xiv commented
You can get close-enough application delays here: https://docs.google.com/spreadsheets/d/1Emevsz5_oJdmkXy23hZQUXimirZQaoo5BejSzL3hZ9I/edit?gid=0#gid=0

2024-12-06 03:18 UTC, zqsz-xiv requested changes
Nice work! Left a few comments.

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +    );
```suggestion
```
can just pass it directly if there's no other effects to add

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +        onConfirm: onConfirm,
```suggestion
        onConfirm: params.onConfirm,
```

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +            state.hasComboStatus(ResourceType.StormCombo, 2);
I don't think you should encode the surging tempest buff duration in the highlight logic here. We try to follow the in-game behavior for highlighting, and as far as I can tell the button just lights up on combo continuation without accounting for the buff's duration.

This condition also doesn't account for situations like the end of a phase before long downtime where you might want to avoid refreshing the buff, and just finish the combo with Storm's Path instead.

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +         state.resources.timeTillReady(WARResourceType.SurgingTempest) <= 30.0)
as above -- highlights should match the in-game behavior, especially since there's weird edge cases with phase/downtime lengths where a premature refresh might be warranted

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +    recastTime: number | ResourceCalculationFn<WARState>,
Does WAR have any GCD abilities that are not 2.5 base + scaled to sks? If not, you might want to omit this parameter and just directly pass `(state) => state.config.adjustedSksGCD()` from within this function.

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +        // To reviewers: should this be done through an internal trait?
I'm fine with leaving the explicit level check.

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +makeAbility_WAR(WARSkillName.Orogeny, 64, WARCooldownType.cd_Upheaval, {
yeah looks like it should be 86

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +    startOnHotbar: false,
not a big deal, but just FYI you don't need to set `startOnHotbar` for abilities with an `autoDowngrade` field

2024-12-06 03:18 UTC, zqsz-xiv commented on src/Game/Jobs/WAR.ts
> +});
I would create two separate cooldowns, and have the activate/release buttons trigger each others' CDs in `onConfirm`. The CD reduction approach makes the progress circle overlay misleading since it always uses the total CD as a denominator when calculating progress.

2024-12-06 14:54 UTC, AkairyuGestalter commented on src/Game/Jobs/WAR.ts
> +});
Take a look at what DNC is doing for Closed Position and Ending, it should have a similar behavior to this

2024-12-07 12:37 UTC, misterperson commented on src/Components/Jobs/WAR.tsx
> +		const reprisalCountdown = this.state.resources.timeTillReady(ResourceType.Reprisal);
Probably not? I can't think of an encounter where the bind would even be applied.

2024-12-08 23:10 UTC, zqsz-xiv approved these changes
LGTM, though looks like CI is failing because your test file is empty. I'm ok with leaving out automated tests, though if there's any buffs/gauge you want to check you should copy the boilerplate in `BlmRotations.test.ts` and set some stuff up; otherwise just delete the file.

LMK when you've fixed that and want to merge + deploy, and I'll hit the button.

2024-12-08 23:10 UTC, zqsz-xiv commented on src/Game/Constants/WAR.ts
> +    ShakeItOffOverTime = "Shake It Off Over Time",
I think the official name has "Over Time" in parentheses: https://garlandtools.org/db/#status/2108

2024-12-13 06:49 UTC, miyehn commented
Are we waiting for more changes before merge? The tests are running fine locally rn 🤔

2024-12-13 06:50 UTC, zqsz-xiv commented
GH actions merges with latest main, which I think has some changes to `DamageStatistics` that need to be updated in the newly-added WAR test. It should pass once those conflicts are fixed.

2024-12-14 06:19 UTC, zqsz-xiv commented
Looks good, anything else you want to change or can we merge + deploy this @misterperson?

2024-12-14 06:20 UTC, misterperson commented
Ready to merge

2024-12-14 06:20 UTC, misterperson commented
There is a comment on Primal Wrath but it's a minor detail for 7.1

2024-12-14 06:21 UTC, merged

2024-12-14 06:26 UTC, zqsz-xiv commented
WAR is now live on the site, thanks again!