Make SkillReadyStatus able to include multiple unavailable reasons
xivintheshell/xivintheshell pull request #83
Opened 2024-12-09 14:19 UTC by miyehn

This fixes [this bug](https://github.com/xivintheshell/xivintheshell/pull/82#issuecomment-2526434551), and combines `status` and `nonCdStatus` in `GameState.getSkillAvailabilityStatus`.

While doing the refactor I also removed `validateAttempt` for SAM's meditate because seems like special case handlings elsewhere already achieved the same effect. Lmk if something broke though 🙏

2024-12-10 00:42 UTC, zqsz-xiv requested changes
The bug I reported is fixed and Meditate works fine, but it looks like secondary CDs aren't being reflected properly for some abilities. Take MCH's Drill (a GCD with a 20s CD scaled to sks at level 90, or 20s unscaled w/ 2 charges at level 100)--on the live site (right) it grays out while on CD, but on left (PR) it's still lit up. I can look into why when I have some free time, or it might be better if @Junie-774 takes a look first since she implemented this.

![image](https://github.com/user-attachments/assets/ebc5d0e5-7ea1-4566-abff-4de403e1d89d)

2024-12-10 00:42 UTC, zqsz-xiv commented on src/Game/Jobs/SAM.ts
> +	validateAttempt: (state) => true,
I'd prefer to keep the explicit validation here in case we ever do refactoring that breaks this invariant, or if we ever decide to turn the job logic into a library consumable by frontends other than our own site.

2024-12-10 02:13 UTC, Junie-774 commented
the logic for the full-ability grey out is a bit flawed now with the new changes...
I think, the condition should be that stacks < 1 for stacking abilities, and just, 'is on CD' for non-stacking abilites with a secondary cooldown

2024-12-10 02:47 UTC, miyehn commented on src/Game/Jobs/SAM.ts
> +	validateAttempt: (state) => true,
Would it make sense if I turn meditate into a skill with secondary cd? I have the intuition that it might let us get rid of some hacks specifically for meditate elsewhere 🤔

2024-12-10 03:25 UTC, zqsz-xiv commented on src/Game/Jobs/SAM.ts
> +	validateAttempt: (state) => true,
We can't directly use a secondary/primary cd here because the GCD roll is scaled to sks and SAM's personal haste buff, while the cooldown field for abilities only takes a scalar. We could turn it into a weaponskill with a secondary cooldown instead, though we'd need to double check to make sure that doesn't break anything.

2024-12-10 03:38 UTC, AkairyuGestalter commented on src/Game/Jobs/SAM.ts
> +	validateAttempt: (state) => true,
It should be fine to define it as a "weaponskill" as far as our code is concerned. DNC does that for Standard and Technical Step.

2024-12-10 04:01 UTC, miyehn commented on src/Game/Jobs/SAM.ts
> +	validateAttempt: (state) => true,
I put its `validateAttempt` back for now. We can change it to a weaponskill in another pr if needed

2024-12-12 07:39 UTC, zqsz-xiv approved these changes
🚀

2024-12-13 06:31 UTC, merged